### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HERNANSEI** [robsonsmartins/php-projects#11]
hi,

Trying to download some magazines, I've got this error.

![image](https://cloud.githubusercontent.com/assets/27975413/25357020/c16c5454-2912-11e7-9f78-35ec9925d260.png)

This is the file

https://issuu.com/ivofarias/docs/edi____o_153_revista_mundo_estranho

**Comment by caiobr70** [comment]
Está apresentando o mesmo problema pra mim.
Same problem here...

**Comment by robsonsmartins** [comment]
This problem is solved! Thanks for reporting, @HERNANSEI!
Esse problema foi resolvido! Obrigado por reportar, @caiobr70!
