### ISSUE TITLE
issuu unable to download files

### ISSUE THREAD

**Issue by ronald009** [robsonsmartins/php-projects#13]
Sir, since a few days am getting a 502 error when trying to download any pdf. either in chrome or firefox. 
Would appreciate it if u could look into the matter sir.
And thanks a lot for the wonderful help you are rendering. cant thank you enough sir.
![image](https://cloud.githubusercontent.com/assets/28040334/25421312/d86ff030-2a79-11e7-8bf7-9e5fc9e80902.png)

**Comment by AmirAmin** [comment]
+1 , Please fix this issue

**Comment by robsonsmartins** [comment]
This problem is solved! Thanks for reporting, @ronald009 and @AmirAmin!
