### ISSUE TITLE
allow to specify the rang when we download by author name

### ISSUE THREAD

**Issue by AlBannaTechno** [robsonsmartins/php-projects#20]
I just need you to add new feature to support set the range when downloading the docs
by author name for example 
from 10 to end
or from book named ... to book/doc.. named ........
the reason 
simply : when we try to download a huge number of files 
then internet cut off 
this will  start download from the Begin 😄

**Comment by robsonsmartins** [comment]
This feature is under construction, and will be available soon

**Comment by robsonsmartins** [comment]
I announce today a new release of the Free Publication Downloader that contains the required feature: you can select which publications to download from an author, or even search publications by word or term. Please test and give me feedback if necessary.
