### ISSUE TITLE
 Invalid string length

### ISSUE THREAD

**Issue by karstennev** [robsonsmartins/php-projects#23]
Error generating PDF: Error getting file 'https://img.yumpu.com/11644636/1097/1219x1600/?quality=85':

**Comment by robsonsmartins** [comment]
This error occurs because of the JavaScript string length limit: https://stackoverflow.com/questions/34957890/javascript-string-size-limit-256-mb-for-me-is-it-the-same-for-all-browsers

**Comment by robsonsmartins** [comment]
The string length limit is 128MB, 256MB or 512MB for many browsers. The generated PDF size is about 600MB.

**Comment by robsonsmartins** [comment]
Updated code to offer a workaround. Please test now. Thanks.
