### ISSUE TITLE
Images downloaded truncated

### ISSUE THREAD

**Issue by Bob1955** [robsonsmartins/php-projects#25]
Contrary to the past experience, I now verified that dowloading any image in landscape format I got the related PDF file truncated on the right side, pratically in square format.
You can refer to the screenshots attached.
Image 1 is the screenshot showing what I was attempting to download from issuu. It shows two pages of a book.
Image 2 is the screenshot showing one page of the dowloaded file. It is related to the right page shown in the image 1.
Is it possible to solve the issue?
Thanks and Best Regards.
Roberto 
<img width="1792" alt="Image 1" src="https://user-images.githubusercontent.com/65771265/82672214-5c622f80-9c40-11ea-8373-d13238035f44.png">
<img width="1792" alt="Image 2" src="https://user-images.githubusercontent.com/65771265/82672229-61bf7a00-9c40-11ea-9204-481ce2324440.png">

**Comment by robsonsmartins** [comment]
Corrected! Please test this now. Thank you for report!
