### ISSUE TITLE
Opção para baixar em alta qualidade

### ISSUE THREAD

**Issue by Shideravan** [robsonsmartins/php-projects#26]
Estou tomando liberdade de falar em português, espero que não se importe.
Bem, de todos os downloaders do Issuu que já encontrei, o seu é o melhor. Não insere bordas brancas, fica ótimo, parabéns!
Mas eu percebi que a qualidade do arquivo extraído e convertido fica inferior ao original do Issuu. Penso que o Issuu te dá uma versão compacta das imagens das páginas quando em zoom out e quando você dá zoom in ele pega a original ou uma imagem que tenha compactação com menos perdas.
Seria possível implementar um "HD Mode" que o script tentasse pegar essas imagens de maior qualidade?

Só para exemplificar o que estou falando, segue um exemplo de uma revista baixada com seu programa e outra diretamente no Issuu.

Issuu (zoom in)
![image](https://user-images.githubusercontent.com/12163923/90323622-1dd7ca80-df3a-11ea-9a49-68b4261ad37a.png)

PDF baixado da mesma publicação usando a aplicação em: https://www.robsonmartins.com/content/info/fpubd/ (zoom in)
![image](https://user-images.githubusercontent.com/12163923/90323640-57a8d100-df3a-11ea-88ca-bc5b01ee78fd.png)
![image](https://user-images.githubusercontent.com/12163923/90323645-7313dc00-df3a-11ea-8d73-0a53efad05aa.png)

Issuu (zoom in)
![image](https://user-images.githubusercontent.com/12163923/90323662-b53d1d80-df3a-11ea-8e55-e8ae0c21ed08.png)

PDF (zoom in)
![image](https://user-images.githubusercontent.com/12163923/90323656-9d659980-df3a-11ea-8c1a-c566b2745e11.png)

**Comment by robsonsmartins** [comment]
Obrigado, @Shideravan!

O Issuu fornece publicamente as imagens em formato JPG em uma única resolução, a que eu uso para criar os PDF's na ferramenta.

As imagens que você vê ao navegar no documento, dentro do site do Issuu, não estão diretamente em formato JPG, PNG, ou qualquer outro lido por um script ou programa comum. São imagens desenhadas por JavaScript no Canvas do Navegador, oriundas de um banco de dados (filestorage) em nuvem, próprio da Issuu, e com API's restritas de acesso (com chaves criptográficas).

Não sei se fui claro, mas para acessar as imagens de alta resolução exibidas no site do Issuu, é necessário possuir essas chaves criptográficas de API, e caso tentasse burlar, se configuraria em invasão ou crime de pirataria (violação de direitos autoriais).

Como minha ferramenta é livre, gratuita, e não viola direitos autorais (somente usa dados publicamente acessíveis pelos sites), a única opção viável para não cometer crimes e violações é oferecer as imagens com a qualidade oferecida.
