### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by mirkocelii** [robsonsmartins/php-projects#27]
Hello, I tried to download few PDFs from Issues and Although I provided my user name and password, it downloaded only the free versione of files (basically 3-4 pages readable).
Is that a bag or what?

**Comment by robsonsmartins** [comment]
Thank you for your reporting! This is a problem with Issuu, that changed of unexpected mode the auth/permission methods. So, unfortunately, I decided disable the login option, because it doesn't work anymore.
