### ISSUE TITLE
Where is the code for the backend/endpoint

### ISSUE THREAD

**Issue by outermedia-cbo** [robsonsmartins/php-projects#28]
Hi Robson,

where can I find the code for the backend/endpoint (e.g. https://www.robsonmartins.com/api/fpubd/clpubd/) ?

Regards
Christoph

**Comment by robsonsmartins** [comment]
Hi Christoph,

Sorry, but this part of my personal site (PHP hosted web code) isn't available. This code isn't open source licenced.

Sorry for inconvenience.

Regards
Robson Martins
