### ISSUE TITLE
publication download not working

### ISSUE THREAD

**Issue by caiobr1901** [robsonsmartins/php-projects#29]
Não funciona pra fazer o download. Dá esta mensagem sempre...
Error listing publication(s) 'https://issuu.com/matsunagamk/docs/matsunaga_et_all_-_o-projeto-de-extensao-universit': Error getting publication properties. URL <https://issuu.com/matsunagamk/docs/matsunaga_et_all_-_o-projeto-de-extensao-universit>

**Comment by robsonsmartins** [comment]
Thanks for reporting.
Corrected! Please take a test now.
