### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by adrianmihalko** [robsonsmartins/php-projects#3]
Dear @robsonsmartins ,

I just found your project, cloned into my local machine, created an index.php with the included test code. But it is now working I get only a blank page. Is your code still working, or issuu changed something?

Here is what I am trying to download.

   $pub_url  = 'monikavaligurova/docs/kenzel_katalog_2016_web01';

Regards,
Adrian

**Comment by robsonsmartins** [comment]
Today, I released a new version (3.0) of Issuu Publication Downloader (Javascript based). The old version (PHP based) is deprecated. Please, test your download now.
