### ISSUE TITLE
[Pedido] Dar suporte a baixar arquivos nxtbook

### ISSUE THREAD

**Issue by Shideravan** [robsonsmartins/php-projects#30]
Seria muito bacana se o FPD desse suporte para baixar em pdf arquivos do nxtbook, como dos exemplos a seguir
https://read.nxtbook.com/walmart/geek/issue_11/cover.html
https://read.nxtbook.com/walmart/gamecenter/issue_71/index.html

**Comment by robsonsmartins** [comment]
Olá! Obrigado pela sugestão. Analisei o site nxtbook, e não encontrei uma forma de acessar na íntegra a imagem das páginas das publicações. Com imagens parciais, o conteúdo do PDF ficaria cortado e inútil. Infelizmente. A única maneira de navegar no conteúdo completo é pelo próprio site, já que um recurso de CORS implementado por eles impede o Javascript de outro site externo manipular esse conteúdo (justamente para evitar cópias e violações de direitos autorais).
