### ISSUE TITLE
404 file not found

### ISSUE THREAD

**Issue by MonneratRJ** [robsonsmartins/php-projects#31]
Trying to download the document on link:
https://www.yumpu.com/es/document/read/63161339/apostila-curso-auxiliar-veterinario-2020-pdf

Returns me a PDF with 164 pages of "file not found"

**Comment by robsonsmartins** [comment]
Unfortunately this is a limitation of the Yumpu website, and is described in the notes on the Free Publication Downloader website (https://www.robsonmartins.com/content/info/fpubd/):

"Some publications from the Yumpu site are not supported (return a PDF with pages containing "HTTP Error 404")."

Unfortunately there is no way to fix it. Other publications within Yumpu are still supported as normal.
