### ISSUE TITLE
Não está sendo possível baixar conteúdo do FlipHTML5

### ISSUE THREAD

**Issue by Shideravan** [robsonsmartins/php-projects#32]
Todo conteúdo que tentei baixar no FlipHTML5, como por exemplo, para o flipbook no endereço a seguir: https://fliphtml5.com/quuaq/mzcf/

Eu recebo a seguinte mensagem:
![image](https://github.com/robsonsmartins/php-projects/assets/12163923/9f1f5157-808c-403f-83a2-1483547471f7)

Poderia dar uma olhada?

**Comment by robsonsmartins** [comment]
Problem fixed. Try downloading again.
Problema corrigido. Tente baixar novamente.
