### ISSUE TITLE
[FPubD] Error download - Calaméo

### ISSUE THREAD

**Issue by AndresGranadaXcrazy** [robsonsmartins/php-projects#34]
Hola

Al intentar descargar algun archivo de calameo, genera el siguiente error

Error generating PDF: Error getting file '/api/fpubd/imgdata.php?url=https%3A%2F%2Fp.calameoassets.com%2F240701170308-a03725d0f4e3b6a0e0dc744c91aa4ad6%2Fp1.jpg&type=image/jpeg': Not loaded.

**Comment by robsonsmartins** [comment]
New method used by Calaméo makes downloading difficult and is incompatible with FPubD.
The solution will be to completely disable support for Calaméo.

El nuevo método utilizado por Calaméo dificulta la descarga y es incompatible con FPubD.
La solución será desactivar completamente el soporte para Calaméo.
