### ISSUE TITLE
Issue in Multidownload

### ISSUE THREAD

**Issue by 1Doudar** [robsonsmartins/php-projects#4]
First, thanks it s very usefull !! 
But somehow get bug in multi download per author
![bug](https://cloud.githubusercontent.com/assets/22326014/18678834/44861ed2-7f55-11e6-9900-d80d6f1d492a.JPG)
 at the end of the 2nd download 

Best,

**Comment by robsonsmartins** [comment]
Thanks for your report! This bug is corrected now. Revision #19. Version 3.0.4. 2016/09/21.

**Comment by 1Doudar** [comment]
Hi,

Martins, the bug was actually only at the last or before last download.

I could download 50 publication easily. Saved me a lot of time.

Huge thanks !!!! It s perfect

Ed
