### ISSUE TITLE
Fail Download All Publications By Author

### ISSUE THREAD

**Issue by cbethter** [robsonsmartins/php-projects#8]
Download All Publications By Author
When selected a Author to download all publication, it shows "no publication ... found"

![erro-issuu-download-author-publication-20161225](https://cloud.githubusercontent.com/assets/23218794/21473075/4589681c-cae0-11e6-8561-8c9b592551c9.png)

**Comment by robsonsmartins** [comment]
For me, it's ok. I downloaded all publications with author name "revistainfo" and ... successfull.
Please, say me the author name used in your search for accurate testing.

**Comment by robsonsmartins** [comment]
Please, retry this download now (with a current version) of Issuu Publication Downloder in my homepage. Thanx, @cbethter.
