### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by Peterspapan** [robsonsmartins/php-projects#9]
Hi @robsonsmartins 

I discovered your project ans I thank you for you work. I had today an issue on downloading a document:
https://issuu.com/marcoacuna/docs/handbook_de_f__sica_parte2
I used the possibility to do download without login details. It worked for another file but I now get an error after all pages of the publication have been precessed "Error in function: undefined" in a JavaScript window,
Could you imagine what went wrong? Many thanks
Kind regards.
@peterspapan

**Comment by robsonsmartins** [comment]
@Peterspapan, thanks!
Yes, I found this error in Firefox. It's because a memory overflow into jsPDF library: your PDF file is very very big! But is successful in Chrome browser. I'll work on a solution for Firefox in a feel days...

**Comment by robsonsmartins** [comment]
@Peterspapan, Can you test the download of your document (https://issuu.com/marcoacuna/docs/handbook_de_f__sica_parte2)? I updated the jsPDF library nowadays, and for me, download it's ok now.

**Comment by Peterspapan** [comment]
Hello Robson,

yes indeed.! It works fine now. That's great. Thank you!

Peterspapan

**Comment by Peterspapan** [comment]
The answer comes a little late, but anyway: thank you. It works.

Saludos.

pedro


On Sat, 20 May 2017 05:39:50 +0200, Robson Martins  
<notifications@github.com> wrote:

>
> @Peterspapan, Can you test the download of your document  
> (https://issuu.com/marcoacuna/docs/handbook_de_f__sica_parte2)? I  
> updated the jsPDF library nowadays, and for me, download it's ok now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



--

**Comment by robsonsmartins** [comment]
Thank you for your report! Gracias!
Robson Martins
